<div
    class="{{$wrapperClasses}}"
    style="{{$wrapperStyle}}"
    data-twill-image-wrapper
>
    @include('image::sizer')
    @include('image::placeholder')
    @include('image::main-image')
</div>
